### ISSUE TITLE
Borrar celdas American Express

### ISSUE THREAD

**Issue by BustamJos3** [BustamJos3/ia4eng_jdbs_afmp_project#14]
# Para dejar el notebook 01-exploracion_datos con solo lo correspondiente a la entrega toca borrar lo que tiene que ver con los datos de american express
Borra las celdas que tienen que ver con esos datos.

**Comment by andrea-mu** [comment]
Hecho, creo
https://colab.research.google.com/drive/19nIgHt2KVWdfmKNWWUNeF8jCed4VFdF7?usp=sharing
