### ISSUE TITLE
update lista de tareas

### ISSUE THREAD

**Issue by BustamJos3** [BustamJos3/ia4eng_jdbs_afmp_project#7]
@andrea-mu agregar enlaces de data sets que has visto.

**Comment by BustamJos3** [comment]
Si ya hiciste la tarea, comenta en el issue que lo hiciste. No tengo ganas de andar preguntando si se hizo algo o no. Tiempo sobra para ponerme a ver si las responsabilidades de alguien más se cumplieron o no.

**Comment by andrea-mu** [comment]
Lo hice
