### ISSUE TITLE
Poner cédula en README

### ISSUE THREAD

**Issue by BustamJos3** [BustamJos3/ia4eng_jdbs_afmp_project#9]
Falta tu c.c en el README; es parte de las rúbricas para el archivo, según lo que está en el curso. @andrea-mu

**Comment by BustamJos3** [comment]
puedes cerrar automáticamente el issue si en el commít pones el número del issue (el que se ve al lado del título #9).

**Comment by andrea-mu** [comment]
no entendí bien el último mensaje pero ya voy a poner la cédula
